apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloraspi
  name: helloraspi-knode2
spec:
  nodeSelector:
    device: knode2
  containers:
    - args:
        - /bin/sh
        - -c
        - 'while true; do echo $(date)": Hello Raspi"; sleep 2; done'
      image: busybox
      name: helloraspi
