apiVersion: v1
kind: Pod
metadata:
  labels:
    run: led-blue
  name: led-blue
spec:
  nodeSelector:
    device: knode3
  containers:
    - image: tingelbuxe/k3s-meetup:ws2813-blue
      imagePullPolicy: Always
      name: led-blue
      securityContext:
        privileged: true
